/**
 * Project: Orange Gerbera
 * -----------------------------------------------------------------------------
 * Copyright (c) 2024-2026 Tai Naoyuki & Kagoshima Takuho.
 * All rights reserved.
 * 
 * This software and any associated documentation are the intellectual property
 * of Tai Naoyuki & Kagoshima Takuho.
 * 
 * Unauthorized copying, use, or distribution of this software,
 * in whole or in part, is strictly prohibited.
 * -----------------------------------------------------------------------------
 */

import { 
  Files, 
  FileText,
  FileDown,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePlusCorner,
  MessageSquareMore,
  MessageSquareText,
  MessageSquareCheck,
  User, 
  UserRoundPlus,
  CircleUserRound,
  UserRoundPen,
  Trash2,
  Building,
  CalendarDays,
  CalendarCog,
  CalendarRange,
  GlobeLock,
  UserRoundKey,
  RefreshCcw,
  ShieldCheck,
  BookUser,
  UsersRound,
  UserRound,
  MailPlus,
  Rows4,
  CalendarArrowUp,
  CalendarPlus,
  CalendarX2,
  List,
  ListStart,
  ListEnd,
  X,
  Save,
  Check,
  Pencil,
  PencilLine,
  UserLock,
  BookDown,
  ArrowLeftRight,
} from 'lucide-angular';

// 使うアイコンをオブジェクトにまとめる
export const customIcons = {
  Files,
  FileText,
  FileDown,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePlusCorner,
  MessageSquareMore,
  MessageSquareText,
  MessageSquareCheck,
  User,
  UserRoundPlus,
  CircleUserRound,
  UserRoundPen,
  Trash2,
  Building,
  CalendarDays,
  CalendarCog,
  CalendarRange,
  GlobeLock,
  UserRoundKey,
  RefreshCcw,
  ShieldCheck,
  BookUser,
  UsersRound,
  UserRound,
  MailPlus,
  Rows4,
  CalendarArrowUp,
  CalendarPlus,
  CalendarX2,
  List,
  ListStart,
  ListEnd,
  X,
  Save,
  Check,
  Pencil,
  PencilLine,
  UserLock,
  BookDown,
  ArrowLeftRight,
};